<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Pegawai;

class PegawaiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Kosongkan tabel terlebih dahulu agar tidak duplikat
        Pegawai::truncate();

        $listGuru = [
            [
                'nama' => 'IRFAN TUNZILA, S.Ag.',
                'nuptk_nip' => '3552755656200022',
                'nuptk' => '3552755656200022',
                'nrg' => '-',
                'nbm' => '-',
                'nik' => '-',
                'ttl' => 'Brebes, 1 Januari 1980',
                'jenis_kelamin' => 'Laki-Laki',
                'pendidikan_terakhir' => 'S1 Agama Islam',
                'tmt' => '2015-01-01',
                'alamat' => 'Brebes, Jawa Tengah',
                'satminkal' => 'SMP Muhammadiyah Tonjong (Induk)',
                'jabatan' => 'KEPALA SEKOLAH',
            ],
            [
                'nama' => 'AHMAD FURQON, S.Ag., S.Pd.',
                'nuptk_nip' => '4843746649200012',
                'nuptk' => '4843746649200012',
                'nrg' => '-',
                'nbm' => '-',
                'nik' => '-',
                'ttl' => 'Brebes, 1 Januari 1982',
                'jenis_kelamin' => 'Laki-Laki',
                'pendidikan_terakhir' => 'S1 Pendidikan',
                'tmt' => '2016-01-01',
                'alamat' => 'Brebes, Jawa Tengah',
                'satminkal' => 'SMP Muhammadiyah Tonjong (Induk)',
                'jabatan' => 'Wakasek, Sarpras, Humas',
            ],
            [
                'nama' => 'SAEFUROKHIM, S.Pd.',
                'nuptk_nip' => '3552751652200002',
                'nuptk' => '3552751652200002',
                'nrg' => '-',
                'nbm' => '-',
                'nik' => '-',
                'ttl' => 'Brebes, 1 Januari 1985',
                'jenis_kelamin' => 'Laki-Laki',
                'pendidikan_terakhir' => 'S1 Pendidikan',
                'tmt' => '2017-01-01',
                'alamat' => 'Brebes, Jawa Tengah',
                'satminkal' => 'SMP Muhammadiyah Tonjong (Induk)',
                'jabatan' => 'Waka Kurikulum',
            ],
            [
                'nama' => 'NISWATUL AENY, S.Pd.',
                'nuptk_nip' => '2857749651300020',
                'nuptk' => '2857749651300020',
                'nrg' => '-',
                'nbm' => '-',
                'nik' => '-',
                'ttl' => 'Brebes, 1 Januari 1988',
                'jenis_kelamin' => 'Perempuan',
                'pendidikan_terakhir' => 'S1 Pendidikan',
                'tmt' => '2018-01-01',
                'alamat' => 'Brebes, Jawa Tengah',
                'satminkal' => 'SMP Muhammadiyah Tonjong (Induk)',
                'jabatan' => 'GURU',
            ],
            [
                'nama' => 'SAEFUDIN, S.Pd.',
                'nuptk_nip' => '7242744647200010',
                'nuptk' => '7242744647200010',
                'nrg' => '-',
                'nbm' => '-',
                'nik' => '-',
                'ttl' => 'Brebes, 1 Januari 1987',
                'jenis_kelamin' => 'Laki-Laki',
                'pendidikan_terakhir' => 'S1 Pendidikan',
                'tmt' => '2018-01-01',
                'alamat' => 'Brebes, Jawa Tengah',
                'satminkal' => 'SMP Muhammadiyah Tonjong (Induk)',
                'jabatan' => 'GURU',
            ],
            [
                'nama' => 'MUKSON, S.Ag., S.Pd.',
                'nuptk_nip' => '1833746649200012',
                'nuptk' => '1833746649200012',
                'nrg' => '-',
                'nbm' => '-',
                'nik' => '-',
                'ttl' => 'Brebes, 1 Januari 1983',
                'jenis_kelamin' => 'Laki-Laki',
                'pendidikan_terakhir' => 'S1 Pendidikan',
                'tmt' => '2016-01-01',
                'alamat' => 'Brebes, Jawa Tengah',
                'satminkal' => 'SMP Muhammadiyah Tonjong (Induk)',
                'jabatan' => 'Ka. Perpus',
            ],
            [
                'nama' => 'NUR LATIFAH, S.Pd.',
                'nuptk_nip' => '9056766666210003',
                'nuptk' => '9056766666210003',
                'nrg' => '-',
                'nbm' => '-',
                'nik' => '-',
                'ttl' => 'Brebes, 1 Januari 1990',
                'jenis_kelamin' => 'Perempuan',
                'pendidikan_terakhir' => 'S1 BK',
                'tmt' => '2019-01-01',
                'alamat' => 'Brebes, Jawa Tengah',
                'satminkal' => 'SMP Muhammadiyah Tonjong (Induk)',
                'jabatan' => 'BK/BP',
            ],
            [
                'nama' => 'YUNIYATI, S.Pd.',
                'nuptk_nip' => '6956766667130112',
                'nuptk' => '6956766667130112',
                'nrg' => '-',
                'nbm' => '-',
                'nik' => '-',
                'ttl' => 'Brebes, 1 Januari 1989',
                'jenis_kelamin' => 'Perempuan',
                'pendidikan_terakhir' => 'S1 Pendidikan',
                'tmt' => '2018-01-01',
                'alamat' => 'Brebes, Jawa Tengah',
                'satminkal' => 'SMP Muhammadiyah Tonjong (Induk)',
                'jabatan' => 'Bendahara BOSP',
            ],
            [
                'nama' => 'SRI PUJIYATI, S.Pd.',
                'nuptk_nip' => '833763664210162',
                'nuptk' => '833763664210162',
                'nrg' => '-',
                'nbm' => '-',
                'nik' => '-',
                'ttl' => 'Brebes, 1 Januari 1986',
                'jenis_kelamin' => 'Perempuan',
                'pendidikan_terakhir' => 'S1 Pendidikan',
                'tmt' => '2017-01-01',
                'alamat' => 'Brebes, Jawa Tengah',
                'satminkal' => 'SMP Muhammadiyah Tonjong (Induk)',
                'jabatan' => 'GURU',
            ],
            [
                'nama' => 'NISWATUN AULA HOPAR, S.Pd.',
                'nuptk_nip' => '1439768669130073',
                'nuptk' => '1439768669130073',
                'nrg' => '-',
                'nbm' => '-',
                'nik' => '-',
                'ttl' => 'Brebes, 1 Januari 1991',
                'jenis_kelamin' => 'Perempuan',
                'pendidikan_terakhir' => 'S1 Pendidikan',
                'tmt' => '2019-01-01',
                'alamat' => 'Brebes, Jawa Tengah',
                'satminkal' => 'SMP Muhammadiyah Tonjong (Induk)',
                'jabatan' => 'Waka Kesiswaan',
            ],
            [
                'nama' => 'NAJDA ALIYATUN NAEZAK, S.Pd.',
                'nuptk_nip' => '8159775676230093',
                'nuptk' => '8159775676230093',
                'nrg' => '-',
                'nbm' => '-',
                'nik' => '-',
                'ttl' => 'Brebes, 1 Januari 1992',
                'jenis_kelamin' => 'Perempuan',
                'pendidikan_terakhir' => 'S1 Pendidikan IPA',
                'tmt' => '2020-01-01',
                'alamat' => 'Brebes, Jawa Tengah',
                'satminkal' => 'SMP Muhammadiyah Tonjong (Induk)',
                'jabatan' => 'Ka. Lab. Ipa',
            ],
            [
                'nama' => 'ADINDA MAYLA RIZQIYATI, S.Pd.',
                'nuptk_nip' => '0842778679230132',
                'nuptk' => '0842778679230132',
                'nrg' => '071111869062025203011',
                'nbm' => '-',
                'nik' => '3329065005000003',
                'ttl' => 'Brebes, 10 Mei 2000',
                'jenis_kelamin' => 'Perempuan',
                'pendidikan_terakhir' => 'S1-P.MTK/UINSAIZU (2023)',
                'tmt' => '4/27/2023',
                'alamat' => 'Dk. Pamijen, RT 002/RW 008 Kec. Tonjong, Kab. Brebes, Prov. Jawa Tengah',
                'satminkal' => 'SMP Muhammadiyah Tonjong (Induk)',
                'jabatan' => 'Bendahara Sekolah',
            ],
            [
                'nama' => 'SOPHIAN BUDIANSYAH, S.Kom.',
                'nuptk_nip' => '5240779680130093',
                'nuptk' => '5240779680130093',
                'nrg' => '-',
                'nbm' => '-',
                'nik' => '-',
                'ttl' => 'Brebes, 1 Januari 1993',
                'jenis_kelamin' => 'Laki-Laki',
                'pendidikan_terakhir' => 'S1 Komputer',
                'tmt' => '2021-01-01',
                'alamat' => 'Brebes, Jawa Tengah',
                'satminkal' => 'SMP Muhammadiyah Tonjong (Induk)',
                'jabatan' => 'Ka. Labkom',
            ],
            [
                'nama' => 'DIANTI PERTIWI, S.Pd.I',
                'nuptk_nip' => '6162777678230203',
                'nuptk' => '6162777678230203',
                'nrg' => '-',
                'nbm' => '-',
                'nik' => '-',
                'ttl' => 'Brebes, 1 Januari 1994',
                'jenis_kelamin' => 'Perempuan',
                'pendidikan_terakhir' => 'S1 Pendidikan Agama Islam',
                'tmt' => '2021-01-01',
                'alamat' => 'Brebes, Jawa Tengah',
                'satminkal' => 'SMP Muhammadiyah Tonjong (Induk)',
                'jabatan' => 'GURU',
            ],
            [
                'nama' => 'NANDANA MAHAZALFAA, S.Pd.',
                'nuptk_nip' => '-',
                'nuptk' => '-',
                'nrg' => '-',
                'nbm' => '-',
                'nik' => '-',
                'ttl' => 'Brebes, 1 Januari 1996',
                'jenis_kelamin' => 'Laki-Laki',
                'pendidikan_terakhir' => 'S1 Pendidikan',
                'tmt' => '2022-01-01',
                'alamat' => 'Brebes, Jawa Tengah',
                'satminkal' => 'SMP Muhammadiyah Tonjong (Induk)',
                'jabatan' => 'GURU',
            ],
            [
                'nama' => 'SUNGGI MURNIASIH, S.Pd.',
                'nuptk_nip' => '-',
                'nuptk' => '-',
                'nrg' => '-',
                'nbm' => '-',
                'nik' => '-',
                'ttl' => 'Brebes, 1 Januari 1995',
                'jenis_kelamin' => 'Perempuan',
                'pendidikan_terakhir' => 'S1 Pendidikan',
                'tmt' => '2022-01-01',
                'alamat' => 'Brebes, Jawa Tengah',
                'satminkal' => 'SMP Muhammadiyah Tonjong (Induk)',
                'jabatan' => 'Tenaga Administrasi',
            ],
            [
                'nama' => 'NUR GHOZIN, S.H., S.Pd.',
                'nuptk_nip' => '1539758661200003',
                'nuptk' => '1539758661200003',
                'nrg' => '-',
                'nbm' => '-',
                'nik' => '-',
                'ttl' => 'Brebes, 1 Januari 1985',
                'jenis_kelamin' => 'Laki-Laki',
                'pendidikan_terakhir' => 'S1 Hukum / S1 Pendidikan',
                'tmt' => '2017-01-01',
                'alamat' => 'Brebes, Jawa Tengah',
                'satminkal' => 'SMP Muhammadiyah Tonjong (Non-Induk)',
                'jabatan' => 'GURU',
            ],
            [
                'nama' => 'SAMIAJI ADITYA NUGROHO GIFA',
                'nuptk_nip' => '-',
                'nuptk' => '-',
                'nrg' => '-',
                'nbm' => '-',
                'nik' => '-',
                'ttl' => 'Brebes, 1 Januari 1998',
                'jenis_kelamin' => 'Laki-Laki',
                'pendidikan_terakhir' => 'S1 Informatika / Komputer',
                'tmt' => '2023-01-01',
                'alamat' => 'Brebes, Jawa Tengah',
                'satminkal' => 'SMP Muhammadiyah Tonjong (Induk)',
                'jabatan' => 'OPERATOR SEKOLAH / Ka. TU',
            ],
            [
                'nama' => 'HERMANTO',
                'nuptk_nip' => '-',
                'nuptk' => '-',
                'nrg' => '-',
                'nbm' => '-',
                'nik' => '-',
                'ttl' => 'Brebes, 1 Januari 1980',
                'jenis_kelamin' => 'Laki-Laki',
                'pendidikan_terakhir' => 'SMA/K Sederajat',
                'tmt' => '2015-01-01',
                'alamat' => 'Brebes, Jawa Tengah',
                'satminkal' => 'SMP Muhammadiyah Tonjong (Induk)',
                'jabatan' => 'TENAGA KEBERSIHAN',
            ],
            [
                'nama' => 'RIVALDO AGUNG PRATAMA',
                'nuptk_nip' => '-',
                'nuptk' => '-',
                'nrg' => '-',
                'nbm' => '-',
                'nik' => '-',
                'ttl' => 'Brebes, 1 Januari 2000',
                'jenis_kelamin' => 'Laki-Laki',
                'pendidikan_terakhir' => 'SMA/K Sederajat',
                'tmt' => '2023-01-01',
                'alamat' => 'Brebes, Jawa Tengah',
                'satminkal' => 'SMP Muhammadiyah Tonjong (Induk)',
                'jabatan' => 'TENAGA KEAMANAN',
            ],
        ];

        foreach ($listGuru as $guru) {
            Pegawai::create($guru);
        }
    }
}